### ISSUE TITLE
crew.stop() is not actually terminating the threads.

### ISSUE THREAD

**Issue by Vladiio** [goodmanship/sqsworkers#26]
As you can see in the ipython session the threads keep "started" state even after invoking crew.stop.

In [8]: crew._daemons
Out[8]:
[<Thread(crew-1981-rps-adev-genetap-genetap-1569403037.05636, started daemon 123145598918656)>,
 <Thread(crew-1981-rps-adev-genetap-genetap-1569403038.567891, started daemon 123145604173824)>]

In [9]: crew.stop()
INFO:root:waiting on background thread to finish

In [10]: crew._daemons
Out[10]:
[<Thread(crew-1981-rps-adev-genetap-genetap-1569403037.05636, started daemon 123145598918656)>,
 <Thread(crew-1981-rps-adev-genetap-genetap-1569403038.567891, started daemon 123145604173824)>]

**Comment by riddhi77** [comment]
Are you using the latest version? Our plan is to rollback to the working version 0.1.12 since this version seems to be having a buggy code.

**Comment by Vladiio** [comment]
@riddhi77 yes, it's the recent release version. I rolled back to the 0.1.12 which doesn't seem to have the issue.

**Comment by riddhi77** [comment]
The latest version 1.1 should not have this issue. Its been rolled back 0.1.12.
